### ISSUE TITLE
Make topic delegate command configurable

### ISSUE THREAD

**Issue by glsf91** [i8beef/HomeAutio.Mqtt.GoogleHome#109]
Can you make the first part used in the delegate command configurable?
I mean the "google/home/" part from google/home/execution/DEVICEID/COMMAND.

**Comment by i8beef** [comment]
Should be configurable (as a base at least) in 2.0 with the new config value `mqtt:topicRoot`. It will still default to the original if omitted.

**Comment by i8beef** [comment]
Closing as fixed, feel free to reopen if you experience issues.
