### ISSUE TITLE
Need help for docker on raspberry pi 3

### ISSUE THREAD

**Issue by minscof** [i8beef/HomeAutio.Mqtt.GoogleHome#136]
I try to run application through docker on a raspberry pi 3 with buster. The container starts, and after a few seconds restarts without log.

I run this command

docker run --restart=always --name homeautio.mqtt.googlehome --user=1000 -dit -p 5000:5000 -v config:/app/config -v logs:/app/logs -e ASPNETCORE_PATHBASE="/google/home" -e TZ=Europe/Paris ghcr.io/i8beef/homeautio.mqtt.googlehome:latest-arm32

I create 2 files in /app/config/
-rw-r--r-- 1 homeautio homeautio 7564 May  4 11:19 googleDevices.json
-rw-r--r-- 1 homeautio homeautio 1447 May  4 11:21 appsettings.Production.json

Do I have to create application in google cloud and setup the nginx proxy to have the application in container running ?  

I need some help.
Thanks

**Comment by minscof** [comment]
I rebuild a docker image for raspberry and now I can launch the application on my raspberry
This is my [dokerfile](https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/files/8633289/Dokerfile.homeautio.rpi.txt)

I change the based images

**Comment by i8beef** [comment]
Did you try a `docker logs homeautio.mqtt.googlehome` by chance? I suspect its failing before even starting the application if you aren't getting logs.
