### ISSUE TITLE
WebUI Checkboxes Not Working

### ISSUE THREAD

**Issue by diabl0w** [i8beef/HomeAutio.Mqtt.GoogleHome#142]
Per title, it seems like the checkboxes in the webui are not working, specifically for "Disabled" and "Will Report State" checkboxes in the edit device page
The boxes check, choose update at the bottom, returns to device overview page, but looking at the config file, it is not updated, or just going back into the device edit page you can see it is no longer selected.
Running latest docker image
Adding/Removing traits in the edit device page works fine, so it doesnt seem to be a general UI/config issue but rather specific to those settings.
On Firefox if that matters, and nothing obvious in logs.
Thanks for the great app!

**Comment by diabl0w** [comment]
Additional Info: stop docker container, set "Will Report State" to true in the config file, start docker container... webui looks fine and has the check box set. but if you then update the device config in webui, it will change this option to false even if you didnt change the checkbox

**Comment by i8beef** [comment]
Confirmed. Ill take a look at it this weekend, and thank you!

**Comment by i8beef** [comment]
3.0.0.15 should build here in a few moments, try that

**Comment by diabl0w** [comment]
youre the man. thank you!
