### ISSUE TITLE
Data from Device to HomeAutio

### ISSUE THREAD

**Issue by NomNom1992** [i8beef/HomeAutio.Mqtt.GoogleHome#143]
Hi sir,
I have studied and implemented your project, and it works very effectively for communication between Home Autio and the Google Home app. Now, I need to add a physical device to complete this course project. However, I'm unsure about what format the data from the device should be in, which protocol to use for sending it, and where to send it.
If you read this, I hope to receive a response from you as soon as possible.
Thank you very much.

**Comment by i8beef** [comment]
This is application is a bridge between Google Home APIs and MQTT, so whatever device you are implementing needs to speak MQTT, and then have its topics mapped/configured as any other device here. Depending on the device and what it does, that could take many different forms, though the easiest is usually to design your device as having a set of "states", which can be updated, and the device responds to the state change to do what it does, and publishes that state change back out when it occurs.

Its most common to have your device publish state topics on any state change:

topic: myDevice/lightOn
value: true
retain: true

And subscribe to known topics that CHANGE that state:

topic: myDevice/lightOn/set
value: false
retain: false (dont retain COMMAND topics)

After the change, it should then publish a "state" topic to publish out the new state of the device too.

This is all fairly common setup for MQTT in a home automation setups, though the topic structures, etc. might take different approaches.
