### ISSUE TITLE
start guide ?

### ISSUE THREAD

**Issue by jmarcgit** [i8beef/HomeAutio.Mqtt.GoogleHome#144]
Hello,

I really want to try this bridge. I use Shelly modules which are supporting MQTT natively. As they also support SSL and authentication therefore  I want to deploy this on the cloud. https://shelly-api-docs.shelly.cloud/gen2/ComponentsAndServices/Mqtt

First I want to use the bridge to define a gate opener device  on the Google side. On the Shelly side, it's a simple switch/relay + state input (closed/open). I guess I can do anything I want as far I can map command and state right ?

Is there a quickstart doc available ?

**Comment by i8beef** [comment]
There is a [Wiki](https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/wiki/Setup) above that you can read through. There is quite a bit of setup to get yourself running as your own service provider, and there is no explicit documentation for running this in a cloud provider, where you'd be on your own. If it were me, and I were doing that, I'd probably setup the proxy in front of it to serve out a limited set of endpoints for instance (just the google / oauth endpoints basically that Google will need to interact with).

Also note Google requires you to use a REAL SSL cert, so your proxy will need to use a LetsEncrypt cert of similar.

Other than that, yes, you should be able to setup your own instance, link it all through your Google developer account, and configure it to send simple open/close intents to pre-specified MQTT topics.

**Comment by jmarcgit** [comment]
thanks !
