### ISSUE TITLE
Where are Docker's volumes?

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.GoogleHome#15]
Hi there. I just ran the docker but can find a way to access the volumes. I do not see any new folder in the host.

**Comment by i8beef** [comment]
You have to create the directory / file first and tell Docker to mount it INTO the running containers FS with the `-v /path/to/your/appsettings.Production.json:/app/appsettings.Production.json`, etc. option.

See the Wiki page for the sample Docker command to see what I mean.

**Comment by GAZ082** [comment]
Yeah, i just ran the docker command "as is". Perhaps you could add to the wiki that the folders should be created, for people like me that always listen about Docker but never actually use. Thanks!

**Comment by GAZ082** [comment]
BTW, those folders should have any default content? Because i ran the docker with bespoke configuration options and those remain empty.

**Comment by i8beef** [comment]
You have to provide your appsettings.Production.json file yourself from the sample in this repo. When mounting a file I'm not aware of how to provide a defaults implementation automatically for that.

Config directory should be empty to start, it's where the app will persist certain things... But this should provide a Google devices config file sample i thought automatically on first creation. I might have missed something there. You can copy the one from this [repo](https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/blob/master/src/HomeAutio.Mqtt.GoogleHome/config/googleDevices.sample.json) directly to start with. It's just an example to give you something to reference right now.

**Comment by GAZ082** [comment]
Thanks Mike for putting up with my newbie questions. I'll close this issue!

**Comment by i8beef** [comment]
No problem, this is a new thing here, so documentation gaps, and even some bugs, are to be expected. Thank you for trying it out, and I'll take a look at the config directory being empty (probably just don't have the files in the repo marked as copy to output). I'll make some additional notes in the docs as well about these pieces.
