### ISSUE TITLE
Docker container keeps restarting.

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.GoogleHome#17]
I started one, stayed running for a few minutes, on "PORTS" 5000:5000 (as shown in container list) but then constantly restarts and the PORTS column is empty,

**Comment by i8beef** [comment]
You're going to have to look at the logs here, as that's not much to go off of.

Remember, you can run docker --logs containerName to see the console output.

**Comment by GAZ082** [comment]
standard_init_linux.go:190: exec user process caused "exec format error"

Looks like its an achitecture issue. Does it support armv6? I'm using it on a Pi Zero.

**Comment by i8beef** [comment]
Ah, no it does not, the docker image is x86. I haven't done an arm docker image for this.

**Comment by GAZ082** [comment]
Oh! So close and yet so far! Is there a way I can cross-compile this by downloading the sources?

**Comment by i8beef** [comment]
I think so... If you pulled everything down and modified the docker file to build against arm versions of the parent images instead of the x86 ones, and just built that locally with docker... I haven't done it before though. To supply docker images for arm, that's basically what I'd do... my laptop is out for repair, but I'll consider my options for arm images on this stuff when it comes back.

**Comment by GAZ082** [comment]
I've been looking and you worked on C#. "Further research" gave me this:

"Note: Pi Zero is not supported because the .NET Core JIT depends on armv7 instructions not available on Pi Zero."

I'm basically screwd on my Zero?

I'd have to do a lot of work to compile in my Pi3, i'd rather wait you get your machine back. You will do it in a matter of minutes, I, in hours!.

**Comment by i8beef** [comment]
Oh that sucks. Yeah sounds like a pi zero is a no go.

**Comment by GAZ082** [comment]
Hi Mike. Did you get your laptop back?

Thanks!

**Comment by i8beef** [comment]
No, its dead, but my new one is supposed to get here Monday. Ill need a day or two to load it though before Im back up and running.

**Comment by GAZ082** [comment]
Hey there. Do you think an ARM version will be available for testing this weekend? It's a long weekend here in Argentina and looks like it's the perfect time for fooling around a couple of hours with this!

Thanks!

**Comment by i8beef** [comment]
I just got my new laptop the other day, so I just got around to looking at this... I did create new Docker builds and a new Dockerfile tonight for an ARM32 Docker image, which you can try... I haven't tried it yet and don't know if its going to fail miserably or not, but its the -arm32 tags [here](https://hub.docker.com/r/i8beef/homeautio.mqtt.googlehome/tags/)

docker run --restart=always --name homeautio.mqtt.googlehome --user=1000 -dit -p 5000:5000 -v appsettings.Production.json:/app/appsettings.Production.json:ro -v config:/app/config -v logs:/app/logs -e ASPNETCORE_PATHBASE="/google/home" -e TZ=America/New_York i8beef/homeautio.mqtt.googlehome:1.0.0.47-arm32

Ill be adding a latest-arm32 build in future builds to simplify a bit.

**Comment by GAZ082** [comment]
Thanks a lot! Tried it out, even when i configured all the paths of the `docker run` command to go to existing ones, i'm having access errors in the docker log, i believe the /app folder belongs to the internal docker storage. I run the app as root in a systemd starter BTW:

```
Unhandled Exception: System.UnauthorizedAccessException: Access to the path '/app/config/tempkey.rsa' is denied. ---> System.IO.IOException: Permission denied
   --- End of inner exception stack trace ---
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize)
   at System.IO.StreamWriter..ctor(String path)
   at System.IO.File.WriteAllText(String path, String contents)
   at Microsoft.Extensions.DependencyInjection.IdentityServerBuilderExtensionsCrypto.AddDeveloperSigningCredential(IIdentityServerBuilder builder, Boolean persistKey, String filename)
   at HomeAutio.Mqtt.GoogleHome.Startup.ConfigureServices(IServiceCollection services) in /app/HomeAutio.Mqtt.GoogleHome/Startup.cs:line 188
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Hosting.ConventionBasedStartup.ConfigureServices(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationServices()
   at Microsoft.AspNetCore.Hosting.Internal.WebHost.Initialize()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at HomeAutio.Mqtt.GoogleHome.Program.Main(String[] args) in /app/HomeAutio.Mqtt.GoogleHome/Program.cs:line 42
```

**Comment by i8beef** [comment]
Well thats actually a good sign that the docker image works at least. You're looking at a Docker permissions issue. Not sure how familiar you are with that issue, but if you're using the command string *I* provide there is a `--user=1000` in there. That means the Docker image is explicitly running with the permissions of whoever user 1000 is on your system, and the mounts need to be owned by that user (or at least read/writable). 

Running Docker containers as root isn't exactly recommended, but its doable, and is the default if you just create the container without that --user switch if I remember right.

**Comment by GAZ082** [comment]
I ran it from the cli, no systemd, with sudo, adding the user corresponding to the UID 1000 to the docker group and same error. Do you know where the /app directory is located in the system?

**Comment by GAZ082** [comment]
Okey, i ran it as root (no --user param) and got errors related to not finding files.

http://termbin.com/u59x

**Comment by i8beef** [comment]
So in Docker, the "docker" group for the system just allows people to interact with docker running on the system, it does nothing for file system access.

The `-v LOCAL:IMAGE` flags in the command map a LOCAL file system location to a mount point in the image (i.e., `-v /var/blah/something:/app` mounts the local directory `/var/blah/something` into the container's file system at `/app`). So in the container, `/app` is at... `/app`. Outside the container, it isn't accessible like that, but the other directories and files you mount INTO it are at whatever location you use in those flags.

The user that Docker runs as (root) can run a container as whatever user you specify, or it will fall back to running it as root. With the `--user` it runs it as whatever UID you specify from the source system, in my example's case, 1000. That means that each of those file/directory volume mounts that I pass in the command must be read/writable by that user (I usually just `chown` them to that user). If you run as root of course, that won't matter, but isn't advised from a general security practices stand point.

You have to actually create the files and directories on the source system that you are mounting into the container before creating the container. Specifically you need to create the

1. appsettings.Production.json file
2. app/config/googleDevices.json file

You can copy the appsettings.json file from the project as a base for the first, and there's a sample googleDevices.json file you can use to build the latter. You could, for instance, start with a googleDevices.json file that has just one device in it for testing, and go through and setup all the pieces you need for that.

**Comment by GAZ082** [comment]
The file does exist and this is the command with the mountpoints:

`sudo docker run --name homeautio.mqtt.googlehome -dit -p 5000:5000 -v appsettings.Production.json:/home/gabriel/googlehome/appsettings.Production.json:ro -v config:/home/gabriel/googlehome/config -v logs:/home/gabriel/googlehome/logs -e ASPNETCORE_PATHBASE="/googlehome" -e TZ=America/Buenos_Aires i8beef/homeautio.mqtt.googlehome:1.0.0.47-arm32`

This is using your command as a guideline. See there is no app referenced anywhere here nor in the wiki when it comes to running the command.

EDIT: oh yes, you use the app folder in the command. Will review it!

**Comment by GAZ082** [comment]
I ran like this:

`sudo docker run --name homeautio.mqtt.googlehome -dit -p 5000:5000 -v appsettings.Production.json:/home/gabriel/googlehome/**app**/appsettings.Production.json:ro -v config:/home/gabriel/googlehome/**app**/config -v logs:/home/gabriel/googlehome/**app**/logs -e ASPNETCORE_PATHBASE="/googlehome" -e TZ=America/Buenos_Aires i8beef/homeautio.mqtt.googlehome:1.0.0.47-arm32
`

No luck either.

**Comment by i8beef** [comment]
Your mounts are wrong if that's your command. Again, its `-v LOCAL:IMAGE`. The right hand side of each of those should NOT change from my example. You should be changing the *left hand* side of the those mounts, like this:

`-v /home/gabriel/googlehome/**app**/appsettings.Production.json:/app/appsettings.Production.json:ro`

**Comment by GAZ082** [comment]
Now we are talking! Thanks a lot! Looks like it's working, still have to configure a few other things but it's promising.

Issue closed!
