### ISSUE TITLE
Evaluate a googleDevices.json editor

### ISSUE THREAD

**Issue by i8beef** [i8beef/HomeAutio.Mqtt.GoogleHome#18]
Consider providing an editor interface for managing the googleDevices.json file.

**Comment by GAZ082** [comment]
Oh boy, i need this SO MUCH!

Edit: the editor should be able not only to create a new file but also modify the existing one.

**Comment by GAZ082** [comment]
I'm not a javascript hacker but do some web things, if you provide templates with clear defined required and optional fields for each type of google device, i may well do a web based editor.

As there is no way to read local files, you would have to copy the existing JSON in a field, modify it with my interface and the copy paste back, but will be much more fast than now.

**Comment by i8beef** [comment]
Yeah its a little tricky if you don't know, and have trouble following, Google's docs on some stuff. My general schema here builds off that, which means that I inherit that complexity and weirdness (i.e., modes, toggles, and camera streams are all... apparently developed by someone other than the rest).

Google's docs aren't the worst I've seen but leaves some blanks.

That said, I tend to make tickets "after" I start on something, at least on personal projects ;-)

I have a semi-working prototype for basic device information, but where all the complexity is is in the editor for the TRAITS section of each device. Theres a lot of nested structures there so right now I'm just exposing them as JSON strings you can edit in the editor... its a hack because I wanted something functional and wasn't ready to think about a REAL UI for those pieces... but those are also the pieces that will benefit the most from an actual editor.

**Comment by GAZ082** [comment]
Oh, alrighty!

**Comment by i8beef** [comment]
So I did flesh this out a little to allow for editing via the UI interface, including links to documentation, and loading of example trait information for adding new traits. I'm calling it for now, as i think this should allow for the expansions I want, and provide enough information in the UI to complete the task. It'd take a bit more of a stateful UI around this to really make it much better.
