### ISSUE TITLE
HomeGraph REQUEST_SYNC issue

### ISSUE THREAD

**Issue by shady2k** [i8beef/HomeAutio.Mqtt.GoogleHome#27]
I have error:
StatusCode: 400, ReasonPhrase: 'Bad Request'

Request have Content-Type: text/plain. This is wrong, need to be Content-Type: application/json.
Method: POST, RequestUri: 'https://homegraph.googleapis.com/v1/devices:requestSync?key=MY_KEY_HERE', Version: 2.0, Content: System.Net.Http.StringContent, Headers:
```
{
  Content-Type: text/plain; charset=utf-8
  Content-Length: 73
}
```

In https://developers.google.com/actions/reference/smarthome/rest/v1/devices/requestSync json looks like:
```
{
  "agentUserId": string,
  "async": boolean
}
```

And in your request:
`{"requestId":null,"agent_user_id":"xxx","payload":null}`

Why do you pass requestId and payload?

**Comment by i8beef** [comment]
Ah, looks like they finally lit that up in the new approach.

https://developers.google.com/actions/smarthome/request-sync

This is the documentation on the old approach, which is implemented here. Your points are valid and I'll take care of them tonight, but I'll probably also look at moving to the new way of doing this all with the token credentials. I never liked that it did this two different ways for this vs reportState.

**Comment by shady2k** [comment]
Thank you, I will wait for fix. Everything works for me, except Home Graph.

**Comment by i8beef** [comment]
Oh yeah, they changed some contracts too. Man I wish there was a mailing list or something for when they change this shit...
