### ISSUE TITLE
Easy way to update the container?

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.GoogleHome#31]
Happy new year!

**Comment by i8beef** [comment]
Happy Holidays sir.

What are you looking for here specifically? I have a script that I run every so often that checks for and updates the local running Docker container from DockerHub if that's what you're looking for.

**Comment by GAZ082** [comment]
Yep! That would be nice!

Thanks a lot for this project man. Cheers!!

**Comment by i8beef** [comment]
I use this. It will check the current container version against the latest on DockerHub, and will pull down a new version if there's updates. Change the command string to suit.

```
#!/bin/bash

REPOSITORY="i8beef/homeautio.mqtt.googlehome:latest"
IMAGENAME="homeautio.mqtt.googlehome"

docker pull $REPOSITORY

LATEST=`docker inspect --format "{{.Id}}" $REPOSITORY`
RUNNING=`docker inspect --format "{{.Image}}" $IMAGENAME`

if [ "$RUNNING" == "$LATEST" ];then
    echo "Up to date"
else
    echo "Updating $IMAGENAME"
    docker stop $IMAGENAME
    docker rm $IMAGENAME
    docker run --restart=always --name $IMAGENAME --user=1000 -dit -p 5000:5000 -v /srv/homeautio.mqtt.googlehome/config:/app/config -v /srv/homeautio.mqtt.googlehome/logs:/app/logs -e ASPNETCORE_PATHBASE="/google/home" -e TZ=America/New_York $REPOSITORY
fi
```

**Comment by GAZ082** [comment]
Worked like a charm, would you add it to the Wiki?

**Comment by i8beef** [comment]
Probably not here... this is just general Docker house keeping, and not really part of this application, I'm only providing it because I happen to have it handy. I think I pulled the skeleton of this off some blog somewhere already.
