### ISSUE TITLE
Web device manager HTTP ERROR 404 when updating device ID. ARM32.

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.GoogleHome#34]
1. Rename a device id.
2. Go back to the menu.
3. Click on the renamed device.
4. HTTP ERROR 404
5. Replace the URL string with the old device id and it loads.
6. Logging out and in does not solve.
7. The settings file is indeed modified.
8. Stopping and restarting the container does not solve the issue.

**Comment by i8beef** [comment]
I'll wager the settings file isn't modified correctly though. Specifically while the device information would get updated, the KEY for the device doesn't change.

I'll put in a fix for it. Good find.

**Comment by i8beef** [comment]
Keeping open until we verify this fixes.

**Comment by GAZ082** [comment]
Solved. Thanks buddy! Great way to start the year!
