### ISSUE TITLE
Suggestion: disable device.

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.GoogleHome#37]
Would be nice to add the option to disable a device so unused ones (unplugged for example) wont show in GH.

A button here:

![image](https://user-images.githubusercontent.com/100194/50578838-d4e30900-0e1d-11e9-9f2b-26f1cc46817e.png)

The effect is that it would comment out all the googleDevices.json block belonging to that device.

**Comment by i8beef** [comment]
Hmmm not a bad idea, but I'd have to think through everything that needs changed for it. JSON comments aren't really a thing, so it'd require quite a number of changes... but this brings up issues in general with the device editor that probably need tackled.

1. Nothing triggers a Google Device Sync, so nothing will be added to Google Home until a sync is triggered manually. Could do something like triggering a REQUEST_SYNC whenever something changes... or just adding a button somewhere to allow people to trigger it that don't know you can do a "Ok Google, Sync my devices"...
2. MQTT subscribe / unsubscribe is handled ONLY on app startup. New traits won't have their subscriptions setup until after a restart, and deleted ones would continue to at least accept messages / state until said restart.

Those should both change here, but I'll have to think about the best way to handle it.

**Comment by i8beef** [comment]
I think I have all the changes developed here... had to refactor a bit to really get everywhere I think I needed. I am not technically handling DISCONNECT intents correctly, but the only thing I could think to do in that case was a global switch for enabling / disabling reportState...  I didn't really want to have it "disable" devices on you... but that's also for a more comprehensive third party service anyway so I'm happy to ignore it.

In the case that a device is disabled, it will stop reporting state, if in use, and it will stop listening to any state topics for the device on MQTT. I should probably drop the state store as well though just to keep things neat... 

I changed a bunch of stuff though, so I'm gonna need to play with it locally a bit this weekend to make sure I didn't miss anything. I'll let ya know when I release another version.

**Comment by i8beef** [comment]
just released a new version. Try that out.

**Comment by GAZ082** [comment]
Works great! I'd grey i out instead of making it red. Grey is more like something is disabled and red is more like something is wrong.

**Comment by i8beef** [comment]
Yeah, I just don't want to setup custom CSS rules for stuff so I worked with what I had. I changed the indicator to be a badge on the list item instead of changing the color though. I wasn't a fan of the red either.
