### ISSUE TITLE
Cannot test in google actions test interface.

### ISSUE THREAD

**Issue by keerttttt** [i8beef/HomeAutio.Mqtt.GoogleHome#55]
When i try to test my app in the Actions console, i get the following error, no matter what i do:
`We're sorry, but something went wrong. Please try again.
'mytestappje' left the conversation`

Also i look at my access logs on my webserver that it's pointing to. It's not making any requests. What am i missing?

**Comment by Vayatoalla** [comment]
Are you trying with an Smart home action?. Something like "turn on the light".
The default query in the Actions Console (Hello xxxx) does not  work in the Smart Home Assistants.

**Comment by i8beef** [comment]
So were you able to get it to work making smart home requests or no?

**Comment by keerttttt** [comment]
Ah, gotta try that. Will do soon

**Comment by i8beef** [comment]
Im gonna close this for now, if you still need help, please feel free to reopen.
