### ISSUE TITLE
Info about the user in the mqtt packet

### ISSUE THREAD

**Issue by Vayatoalla** [i8beef/HomeAutio.Mqtt.GoogleHome#57]
Would it be possible to have information about the user ID in the mqtt package ?: Because I would like to be able to turn on different devices depending on the Google user.

**Comment by i8beef** [comment]
No, I'm afraid not. Not only does Google not supply this information in INTENTS, but it would require moving away from simple single value payloads, which is a fundamental foundation of this implementation, so even if they started supplying that, it wouldn't be something I would include.
