### ISSUE TITLE
Cannot configure a Door device

### ISSUE THREAD

**Issue by Vayatoalla** [i8beef/HomeAutio.Mqtt.GoogleHome#58]
I am trying to configure a Garage Door in homeautio. My first concern is that when I use the device type "google/home/Garage" homeautio fails at start. I suppose it is because this device id is not defined in the code, as I dont see it in the Device Type in the homeautio web page. So, I am trying with the 'Door' device type.

Setting the 'Door' device type, the APP starts without complaining, but when I try to see my device in the Google Home APP its icons uppear like 'configuration pending'. I attach a screenshot with the icon that I see. Also, I cannot do any command with this device. If I only change the device type from DOOR to SWITCH (for example) in the googleDevices.json (without changing nothing more), I can see the device as configured in the Google Home APP, but with the SWITCH icon and commands.

Here is my JSON of the device.

```
"google/home/GarageDoor": {
    "id": "google/home/GarageDoor",
    "type": "action.devices.types.DOOR",
    "disabled": false,
    "willReportState": true,
    "roomHint": "Garage",
    "name": {
      "defaultNames": [],
      "name": "Puerta Garage",
      "nicknames": []
    },
    "deviceInfo": {
      "manufacturer": "ACME",
      "model": "GDoorOpener",
      "hwVersion": "1.0",
      "swVersion": "1.0"
    },
    "traits": [
      {
        "trait": "action.devices.traits.OpenClose",
        "attributes": null,
        "queryOnlyOpenClose": false
        "commands": {
          "action.devices.commands.OpenClose": {
            "openPercent": "google/home/GarageDoor/setPercent"
          }
        },
        "state": {
          "openPercent": {
            "topic": "google/home/GarageDoor",
            "googleType": "numeric",
            "valueMap": [
              {
                "mqtt": "open",
                "type": "value",
                "google": 100
              },
              {
                "mqtt": "close",
                "type": "value",					
                "google": 0
              } ] } } } ],
       "customData": null
},
```

![GarageIcon](https://user-images.githubusercontent.com/32686442/61438769-7fe18d00-a940-11e9-8218-9f7a33e4b63d.jpg)

**Comment by i8beef** [comment]
Google doesn't actually support doing anything in the Home app except for lights and switches I think. I fully encourage you to complain loudly at them, because its pretty stupid they've let it go this long...
