### ISSUE TITLE
gactions test error.

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.GoogleHome#60]
Hey. Just came from honeymoon after having all my devices unplugged. Started server, updated the docker image and everything seemed to work but when shout a command GA said there was a problem.

Tried the ./gactions test --action_package action.json --project  asistente-xxx --preview_mins 9999999 thing again and failed:

```
./gactions test --action_package action.json --project  asistente-de8b4 --preview_mins 9999999
Pushing the app for the Assistant for testing...
ERROR: Failed to test the app for the Assistant
ERROR: Internal error encountered.
```
The login page works fine, but cant find the service in the list of vendors in the Google Home app.

Thanks!

**Comment by i8beef** [comment]
Yeah they aren't exactly good at providing any useful debugging tools are they? Ive had mine drop as well and had to restart the testing again and ran into those kinds of issues too. It seems that Google changed something that expired all of our testing sessions and required starting them again, but they also changed something that broke all of the methods to actually do that for existing projects.

What we found was that there seemed to be something related to the Goolge Actions Console Fullfillment URL changing... like something must have been added behind the scenes that when you change that it registers it somewhere necessary for testing. For some existing projects that already exist, they basically are missing whatever that registration is. We found changing the fullfillment URL to something else, saving it, and then changing it right back seemed to allow us to start the "test" session again.

Try that and see if you can put it back into test mode after that. I dont remember if I did it through gactions after the fix, or if I just clicked the test button in the Google Actions Console.

**Comment by GAZ082** [comment]
Tried and failed!

**Comment by GAZ082** [comment]
Oh wait, it worked but yet in the CLI shows the error. Odd.

**Comment by i8beef** [comment]
So you back to working? I also saw some weirdness from gactions, but never got to the bottom of it. It might be a good thing to raise over here: https://github.com/actions-on-google/smart-home-nodejs/issues

**Comment by i8beef** [comment]
Closed for inactivity
