### ISSUE TITLE
Docker dies immediately

### ISSUE THREAD

**Issue by gordontervit** [i8beef/HomeAutio.Mqtt.GoogleHome#61]
Getting error 
{"log":"standard_init_linux.go:178: exec user process caused \"exec format error\"\r\n","stream":"stdout","time":"2019-10-20T02:12:19.987354326Z"}

**Comment by i8beef** [comment]
Are you sure you're using the right image for your architecture?

**Comment by gordontervit** [comment]
Hmm, it's armv7/arm32 as it's a raspPi, and I (stupidly) assumed the docker pull command would grab the correct archticture, but docker image inspects says it's got the amd64 version. Is there a way to force it to pull the arm32?

**Comment by Vayatoalla** [comment]
Yes. You only need to add a label at the end of the image name: i8beef/homeautio.mqtt.googlehome:latest-arm32

I am running homeautio in a Raspberry with Raspbian:
# uname -a
Linux rasp3 4.19.66-v7+ #1253 SMP Thu Aug 15 11:49:46 BST 2019 armv7l GNU/Linux

**Comment by gordontervit** [comment]
Thanks, adding the :latest-arm32 resolved the issue. The container is running, I've got google integrated, just need to puzzle out the mappings in googleDevices.json now to get the basic cbus on/off and dimming.
