### ISSUE TITLE
If it work let your project being viral with a step by step video tutorial... I'm searching for this and never fin something simple

### ISSUE THREAD

**Issue by EdIVeDeR** [i8beef/HomeAutio.Mqtt.GoogleHome#62]

**Comment by i8beef** [comment]
If you have documentation recommendations, Im all ears, but I am not the type to do video tutorials.

Unfortunately you aren't going to find an easy solution for this unless you use a rolled solution like OpenHab, HomeAssistant, etc. where someone else runs the cloud implementation pieces. Google's entire implementation is geared toward cloud based commercial development partners, not do-it-yourself implementations. If you want a standalone fulfillment like this: its gonna be rough.
