### ISSUE TITLE
how to get the agentUserId

### ISSUE THREAD

**Issue by Laurentmichel4irulez** [i8beef/HomeAutio.Mqtt.GoogleHome#63]
I'm following you wiki to setup the HomeAutio.
Can you tell me how to get the agentUserId to put in the appsettings.Production.json

Thanks

**Comment by i8beef** [comment]
You can just pass "homeautio" for this. Google's API is more geared toward large third party developers that fulfill requests for all their users, and they expect them to send the user id of each with the requests with this variable.

When you are running your own fulfillment like this, you are the only user, so you can put literally almost anything in this field.
