### ISSUE TITLE
When linking service to GH. "Could not update settings. Check connection."

### ISSUE THREAD

**Issue by GAZ082** [i8beef/HomeAutio.Mqtt.GoogleHome#64]
Hey there! Merry christmas and happy new year!

I'm having some trouble re-adding my service. I'm getting the error in the subject. Checked previous closed issues and could not find a solution.

Video of what I do:

https://www.youtube.com/watch?v=i4brT-v5cbs&feature=youtu.be

(sorry for my creepy respiration and my wife's (yes, joined the club this year) mouse clicks LOL)

Here is the log in case you can give a look, will expire in a week:

https://pastebin.com/NFLx0KNs

Thanks a lot!

**Comment by i8beef** [comment]
I think the auth looks good. It looks instead like its unable to connect to the sync endpoint. Obviously you'll want to make sure that endpoint is accessible from outside and is hosted at the right URL that Google thinks its at. I HAVE seen Google's side get hosed and I had to go in and CHANGE the URL in the Actions Console to something else, save it, then change it back and save again. There's something tied to that save action in their Actions Console that refreshes some things.

**Comment by GAZ082** [comment]
Thanks. I tried what you said and did not help. I entered  to the URLs and both say invalid request as output (one in Json, the other CSS styled) so I believe they are well served.

**Comment by i8beef** [comment]
Are you seeing any indications in the log that there's actually a request to the fullfillment url "smarthome" endpoint tied to one of these attempts? Immediately after one of these auths you should see a SYNC call to get a device list from it.

You had this working before right? What changed? (i.e., so we can narrow down your issue)

**Comment by GAZ082** [comment]
I see no SYNC in the logs: https://pastebin.com/raw/JvQHudbU (1 month due date).
I changed the domain from domain.com to services.domain.com. Reconfigured everything to point to that new url. Google Actions, your app, etc.

Happy new year!

**Comment by i8beef** [comment]
If you aren't seeing the followup requests, I would think you have an issue in connectivity somewhere. One of

1. Google fullfillment URL wrong in Google Actions
2. OAuth Authority / Origin settings in config file being wrong
3. Expired signing key
4. Proxy configuration?

I really should add an option on the next release that lets you download the active SYNC payload too... it would be helpful for passing through Google's validator to look for errors, but I don't think thats the issue if you haven't changed anything there. It sounds a lot more like connectivity being configured wrong somewhere.

**Comment by GAZ082** [comment]
I'll reconfigure everything from scratch. I'll hit the wiki and let you know.

**Comment by GAZ082** [comment]
Okey, found that i was missing to reconfigure the new domain in the Fulfillment URL section of the action.

Thanks!
