### ISSUE TITLE
Guide to hosting on azure web app

### ISSUE THREAD

**Issue by dwdickens** [i8beef/HomeAutio.Mqtt.GoogleHome#66]
Would it be possible to have a short guide on hosting using azure web apps? 

I was able to publish using visual studio 2017 to an azure web app (myapp.azurewebsites.net) in one click but not sure what instruction to follow next. 

I think this would be a really popular option for deploying because should dramatically reduce amount of set up, and basic azure hosting is free!

**Comment by i8beef** [comment]
Unfortunately I'm an Azure novice so I really wouldn't know what you'd need to do. If you write down what you have to do to get it working there though I'd consider adding it to the wiki here for others.

Just remember, this app is a standalone application that exposes its own, UNENCRYPTED, web end point. Even if you get it running somewhere, you still need to (a) not expose it publically without (b) proxying it through something that provides the SSL/TLS encryption.

**Comment by i8beef** [comment]
Closing as stale / out of scope.
