### ISSUE TITLE
Error when creating traits - Device does not support trait type

### ISSUE THREAD

**Issue by sognen** [i8beef/HomeAutio.Mqtt.GoogleHome#85]
Hi,
First, many thanks for this app - much appreciated. 

When creating a trait and clicking the Create button I get an error message saying that it is not a valid trait type and device does not support trait type, e.g., 

**Error
The value 'action.devices.traits.ArmDisarm' is not valid for Trait.
Device does not support trait type**

I have tried with a few device types and traits - all giving the same error. 

New Device and new trait:
 After creating the device I can see the definition in the googleDevice file.
After loading the trait template and clicking the Create button I get the above error message. 

Existing Device and new trait:
Same as a above. Tried with dimmeableLight and creating trait ColorSetting

Existing Device and update existing trait:
Appears to be working.

Nothing to be found in the the log (log level set to error).

What I have tried so far:
- Updated to latest build (today)
- Removed and recreated the container
- Using the most current googleDevices.json file as a starting point.
- Created multiple devices/traits all producing the same error.

The devices and traits I created a few months back continue to work.

Best Regards,
Cato

**Comment by i8beef** [comment]
Yes, the app now enforces the supported traits that Google has listed in their documentation. ArmDisarm is only supported on SecuriySystem device type. Is there another device type that you expect it on?

https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/blob/master/src/HomeAutio.Mqtt.GoogleHome/Models/DeviceMetadata.cs

**Comment by sognen** [comment]
Hi,
Understood. When I mentioned that I created an ArmDisarm trait it was for a device with type SecuritySystem.  Similarly when creating a device of type Scene I get the error message when trying to create a trait Scene. All is done using the webui.

**Comment by i8beef** [comment]
{ DeviceType.Scene, new List<TraitType> { TraitType.Scene } },

That should be supported. What error are you getting?

**Comment by sognen** [comment]
I get the same error message as with security system, albeit different trait of course.

Error
The value 'action.devices.traits.Scene' is not valid for Trait.
Device does not support trait type

**Comment by i8beef** [comment]
Hmm yeah looks to be a bug I introduced in the editor. Ill try and get a fix out tonight.

**Comment by i8beef** [comment]
Try the latest. Should be fixed.

**Comment by sognen** [comment]
Thanks - working now, much appreciated.
