### ISSUE TITLE
New Media Device Traits

### ISSUE THREAD

**Issue by diabl0w** [i8beef/HomeAutio.Mqtt.GoogleHome#90]
It looks like google added traits for changing channels and volume https://developers.googleblog.com/2020/07/announcing-new-smart-home-shed-types-and-traits.html?m=1

Will we be able to use these? Can we use them now without any changes?

**Comment by i8beef** [comment]
The current implementation should support these devices and traits already.

**Comment by diabl0w** [comment]
> The current implementation should support these devices and traits already.

awesome! thanks!
