### ISSUE TITLE
How to run the stand alone app?

### ISSUE THREAD

**Issue by rockstar2020** [i8beef/HomeAutio.Mqtt.GoogleHome#94]
I'm very interested to deploy your project on my RPi but I don't know how I can run the app in stand alone mode?
Do you I need to install a web server like Apache first?
I went through you wiki but couldn't find anywhere referencing it. 
Apologies if this question has an obvious answer and I understand that it doesn't fit in the "Issue" section of the github. 

Many thanks

**Comment by i8beef** [comment]
You run this in Docker at port 5000, and then proxy it through a webserver like Apache / nginx, as detailed here: https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/wiki/Setup

**Comment by rockstar2020** [comment]
Thanks, I'll give it a try.
Great work!

**Comment by rockstar2020** [comment]
Hi again,
I'm not very familiar with docker and hence having a hard time setting up the app.
I've pulled your docker image on my RPi but don't know how to edit the config file inside the docker image/volume.
Can you point me to the right direction?
I'm pretty sure after changing the config file I can manage the rest. 
Very much appreciate it. 
Thanks

**Comment by i8beef** [comment]
You don't edit the config file in the application, you create an application.Production.config on the mounted config directory as specified in the documentation: https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/wiki/Setup:-Application

The volume mount for docker (-v option in the provided docker command) specifies a directory on the HOST to mount into the CONTAINER at a specific location. I.e., once you start it up with that, you don't have to get into the container, anything you add to that config directory is directly visible to the app in the container.

You can copy the appsettings.json from the repo as a base to get you started: https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/blob/master/src/HomeAutio.Mqtt.GoogleHome/appsettings.json

And then set it up using the docs for that file: https://github.com/i8beef/HomeAutio.Mqtt.GoogleHome/wiki/Config:-appsettings.Production.json

**Comment by i8beef** [comment]
Closing as stale
